/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        secondary: {
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
        accent: {
          50: '#FFF7ED',
          100: '#FFEDD5',
          200: '#FED7AA',
          300: '#FDBA74',
          400: '#FB923C',
          500: '#F97316',
          600: '#EA580C',
          700: '#C2410C',
          800: '#9A3412',
          900: '#7C2D12',
        },
        neutral: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Merriweather', 'serif'],
      },
      spacing: {
        '128': '32rem',
      },
      animation: {
        'page-turn': 'pageTurn 0.5s ease-in-out',
        'fade-in': 'fadeIn 0.3s ease-in',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 8s ease-in-out infinite 2s',
        'float-slow': 'float 10s ease-in-out infinite 4s',
        'spin-slow': 'spin 20s linear infinite',
        'float-book': 'floatBook 8s ease-in-out infinite',
        'float-book-delayed': 'floatBook 10s ease-in-out infinite 3s',
        'float-book-slow': 'floatBook 12s ease-in-out infinite 6s',
        'page-float': 'pageFloat 6s ease-in-out infinite',
        'page-float-delayed': 'pageFloat 8s ease-in-out infinite 2s',
        'page-float-slow': 'pageFloat 10s ease-in-out infinite 4s',
        'letter-float': 'letterFloat 7s ease-in-out infinite',
        'letter-float-delayed': 'letterFloat 9s ease-in-out infinite 2.5s',
        'letter-float-slow': 'letterFloat 11s ease-in-out infinite 5s',
        'reading-particle': 'readingParticle 4s ease-in-out infinite',
        'reading-particle-delayed': 'readingParticle 5s ease-in-out infinite 1.5s',
        'reading-particle-slow': 'readingParticle 6s ease-in-out infinite 3s',
      },
      keyframes: {
        pageTurn: {
          '0%': { transform: 'rotateY(0deg)', opacity: '1' },
          '100%': { transform: 'rotateY(30deg)', opacity: '0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '25%': { transform: 'translateY(-20px) rotate(1deg)' },
          '50%': { transform: 'translateY(-10px) rotate(-1deg)' },
          '75%': { transform: 'translateY(-15px) rotate(0.5deg)' },
        },
        floatBook: {
          '0%, 100%': { transform: 'translateY(0px) rotate(12deg)' },
          '25%': { transform: 'translateY(-25px) rotate(15deg)' },
          '50%': { transform: 'translateY(-15px) rotate(9deg)' },
          '75%': { transform: 'translateY(-20px) rotate(18deg)' },
        },
        pageFloat: {
          '0%, 100%': { transform: 'translateY(0px) rotate(45deg) scale(1)' },
          '33%': { transform: 'translateY(-30px) rotate(50deg) scale(1.1)' },
          '66%': { transform: 'translateY(-10px) rotate(40deg) scale(0.9)' },
        },
        letterFloat: {
          '0%, 100%': { transform: 'translateY(0px) scale(1)', opacity: '0.3' },
          '50%': { transform: 'translateY(-20px) scale(1.2)', opacity: '0.6' },
        },
        readingParticle: {
          '0%, 100%': { transform: 'translateY(0px) scale(1)', opacity: '0.4' },
          '25%': { transform: 'translateY(-40px) scale(1.5)', opacity: '0.8' },
          '50%': { transform: 'translateY(-20px) scale(1.2)', opacity: '0.6' },
          '75%': { transform: 'translateY(-30px) scale(0.8)', opacity: '0.3' },
        },
      },
    },
  },
  plugins: [],
};